# Generated by Django 5.2.7 on 2025-10-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
    ]
