# Generated by Django 5.2.7 on 2025-11-02 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='message',
            name='profile_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
            preserve_default=False,
        ),
    ]
