# Generated by Django 5.2.7 on 2025-11-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_message_profile_id_message_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='ticket_id',
            new_name='ticket',
        ),
    ]
