# Generated by Django 5.2.7 on 2025-11-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
